@base = http://localhost:3000

### 1. Register user sans infos facultatives
# @name registerReq
POST {{base}}/api/v1/auth/register
Content-Type: application/json

{"courriel": "bobby@gmail.com", "pseudonyme": "Tristesse38", "motDePasse": "bobby123"}

###
@utilisateurId = {{registerReq.response.body.id}}

### 2. Register user avec infos facultatives
POST {{base}}/api/v1/auth/register
Content-Type: application/json

{"courriel": "jean@gmail.com", "pseudonyme": "Jean_ai_plein_mon_cass", "motDePasse": "jean123", "nom": "Jean Souffre", "avatarUrl": "https://www.pinclipart.com/picdir/middle/529-5291405_peace-sign-clipart-avatar-peace-symbol-transparent-background.png", "bio": "Juste un dude tanné. Je veux des vacaaaaances...!"}

### 3. Créer un compte admin
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{"courriel": "admin@gmail.com", "pseudonyme": "admin01", "motDePasse": "admin123", "nom": "Claude Cobra", "avatarUrl": "https://i.pinimg.com/originals/d4/92/a0/d492a0a000b65aa5bce960e1fd782b1d.png", "bio": "Hard at work pour le mieux-être de tous! La vie est belle on lâche pas!", "codeAdmin": "admin123"}

### 4. Login en tant qu'admin et récupérer le token
# @name loginAdmin
POST {{base}}/api/v1/auth/login
Content-Type: application/json

{
  "courriel": "admin@gmail.com",
  "motDePasse": "admin123"
}

###
@adminToken = {{loginAdmin.response.body.token}}

### 5. Login en tant qu'utilisateur et récupérer le token
# @name loginReq
POST {{base}}/api/v1/auth/login
Content-Type: application/json

{
  "courriel": "bobby@gmail.com", "pseudonyme": "Tristesse38", "motDePasse": "bobby123"
}

### ----- Journal -----

### 6. Recevoir mes journal
@authToken = {{loginReq.response.body.token}}
###
GET {{base}}/api/v1/journal
Authorization: Bearer {{authToken}}

### 7. Créer une entrée de journal
POST {{base}}/api/v1/journal
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "humeur": 2,
    "energie": 1,
    "sommeil": 3,
    "anxiete": 5,
    "gratitude": "Test"
}

### 8. Créer une entrée dans le journal
POST {{base}}/api/v1/journal
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "humeur": 5,
  "energie": 4,
  "sommeil": 5,
  "anxiete": 1,
  "gratitude": "Superbe séance de sport ce matin et un bon café au soleil"
}

### 9. Créer une entrée dans le journal
POST {{base}}/api/v1/journal
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "humeur": 3,
  "energie": 2,
  "sommeil": 5,
  "anxiete": 4,
  "gratitude": "Content d'avoir terminé mes examens à temps"
}

### 10. Récupérer une entrée d'un journal avec une date
GET {{base}}/api/v1/journal/2026-08-13
Authorization: Bearer {{authToken}}

### 11. Modifier une entrée d'un journal d'une date passée
PATCH {{base}}/api/v1/journal/2026-08-13
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "gratitude": "Test patch"
}

### 12. Modifier une entrée dans un journal avec des données invalides
PATCH {{base}}/api/v1/journal/2026-08-13
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "utilisateurId": "test"
}

### 13. Recevoir les stats d'un journal 
GET {{base}}/api/v1/journal/stats?range=15d
Authorization: Bearer {{authToken}}

### 14. Login en tant que alice et récupérer le token
# @name loginAlice
POST {{base}}/api/v1/auth/login
Content-Type: application/json

{
  "courriel": "alice@example.com", "pseudonyme": "AliceZen", "motDePasse": "Password123!"
}

###
@aliceToken = {{loginAlice.response.body.token}}

### 15. Recevoir les correlations d'un utilisateur
GET {{base}}/api/v1/journal/insights
Authorization: Bearer {{aliceToken}}

### ----- Ressources -----

### 16. Recevoir la totalité des ressources
GET {{base}}/api/v1/resources

### 17. Filtre par durée maximale uniquement (ex: max 6 minutes)
GET {{base}}/api/v1/resources?dureeMax=6

### 18. Combinaison : Recherche + Durée Max + Pagination
GET {{base}}/api/v1/resources?recherche=anxie&dureeMax=6&page=1&limit=5

### S'assurer que le id existe bien dans la BDD (table Ressource)
@ressourceId = 01354bf9-6b60-40bc-af53-4df2d39af071

### 19. Recevoir une ressource avec son id
GET {{base}}/api/v1/resources/{{ressourceId}}

### 20. Creer une ressource en tant qu'admin
POST {{base}}/api/v1/resources
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "titre": "Survivre au hackathon, comment gérer le stress",
  "contenu": "C'est impossible",
  "url": "https://zombo.com/",
  "categorie": "ANXIETE",
  "type": "Exercice mental",
  "duree": 5,
  "niveau": 1
}


### ----- Me -----

### 21. Recevoir les données à exporter
GET {{base}}/api/v1/me/export
Authorization: Bearer {{authToken}}

### 22. Exporter les données en CSV
GET {{base}}/api/v1/me/export?format=csv
Authorization: Bearer {{authToken}}

### 23. Supprimer mon utilisateur
DELETE  {{base}}/api/v1/me/
Authorization: Bearer {{authToken}}

###### MESSAGES ##############################

### 24. Login en tant qu'utilisateur et récupérer le token
# @name loginReq
POST {{base}}/api/v1/auth/login
Content-Type: application/json

{
  "courriel": "sara@example.com",
  "motDePasse": "Password123!"
}

### 25. Voir les messages de l'utilisateur u3 avec l'utilisateur u1
GET {{base}}/api/v1/messages/u1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 26. Voir toutes les conversations (le dernier message de chacune)
GET {{base}}/api/v1/messages
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 27. Envoyer un message a l'utilisateur u2
POST {{base}}/api/v1/messages/u2
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "sujet": "Ca va?",
    "contenu": "Aurais tu le temps de parler du deuil?"
}

### 28. Voir les messages de l'utilisateur u3 avec l'utilisateur u2
GET {{base}}/api/v1/messages/u2
Authorization: Bearer {{authToken}}
Content-Type: application/json


############ USERS #############################

### 29. Bloquer utilisateur u5
POST {{base}}/api/v1/users/u5/block
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 30. Essayer d'envoyer un message a u5 après l'avoir bloqué
POST {{base}}/api/v1/messages/u5
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "sujet": "test de bloc",
    "contenu": "Aurais tu le temps de parler du blocage?"
}


### 31. afficher un utilisateur
GET {{base}}/api/v1/users/u5
Authorization: Bearer {{authToken}}
Content-Type: application/json



############ ME #############################

### 32. changer la bio du user u3
PATCH {{base}}/api/v1/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "bio": "Moi j'aime les chars pis le biseboll"
}

### 33. changer les donnes de privacy pour rendre le profil prive
PATCH {{base}}/api/v1/me/privacy
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "visibilite": "PRIVE"
}

### 34. changer les donnes de privacy pour rendre le profil public
PATCH {{base}}/api/v1/me/privacy
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "visibilite": "PUBLIC"
}

### 35. rendre a nouveau le profil privé pour le prochain test
PATCH {{base}}/api/v1/me/privacy
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "visibilite": "PRIVE"
}


### 36. afficher un utilisateur (introuvable car privé)
GET {{base}}/api/v1/users/u3
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 36. Créer un signalement
POST {{base}}/api/v1/reports
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "categorie": "INQUIETANT"
}

### 37. Recevoir les signalements
GET {{base}}/api/v1/admin/reports
Authorization: Bearer {{adminToken}}

### 38. Traiter un rapport
PATCH  {{base}}/api/v1/admin/reports/sig1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "statut": "TRAITE"
}

### 39. Recevoir des stats (administrateur)
GET {{base}}/api/v1/admin/stats
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "statut": "TRAITE"
}

### 40. Suspendre un utilisateur
PATCH {{base}}/api/v1/admin/users/u1/suspend
Authorization: Bearer {{adminToken}}

# SECTION D : Groupe de soutien

### 1. Création du groupe privé par le modérateur
@name creationGroupe
POST {{base}}/groupes
Authorization: Bearer {{tokenModo}}
Content-Type: {{contentType}}

{
    "thematique": "Apprivoiser l'anxiété sociale",
    "description": "Un espace sûr pour échanger sur l'anxiété au quotidien.",
    "regles": "Respect, bienveillance et confidentialité obligatoires.",
    "visibilite": "PRIVE"
}

### Stocker l'ID du groupe créé
@groupeId = {{creationGroupe.response.body.id}}

### 2. Julie cherche le groupe (Vérification de la visibilité)
GET {{base}}/groupes?recherche=anxiété
Authorization: Bearer {{tokenJulie}}

{
    "presentation": "Bonjour, je m'appelle Julie et je souffre d'anxiété sociale depuis 2 ans. Je cherche un groupe pour m'aider à progresser."
}

### Stocker l'ID de la demande d'adhésion
@demandeId = {{demandeJulie.response.body.demande.id}}


### 3. Le modérateur accepte la demande de Julie
PUT {{base}}/groupes/demandes/{{demandeId}}
Authorization: Bearer {{tokenModo}}
Content-Type: {{contentType}}

{
    "statut": "ACCEPTEE"
}


### 4. Julie publie son premier message dans le groupe
@name publicationJulie
POST {{base}}/groupes/{{groupeId}}/publications
Authorization: Bearer {{tokenJulie}}
Content-Type: {{contentType}}

{
    "contenu": "Merci de m'avoir acceptée ! Est-ce que quelqu'un a des astuces pour gérer les crises d'angoisse en public ?"
}

### Stocker l'ID de la publication
@publicationId = {{publicationJulie.response.body.id}}



### 5. Un autre membre (ou le modo) répond au message de Julie
@name commentaireModo
POST {{base}}/groupes/publications/{{publicationId}}/commentaires
 Authorization: Bearer {{tokenModo}}
Content-Type: {{contentType}}
{
    "contenu": "Bienvenue Julie ! Personnellement, la méthode du 5-4-3-2-1 m'aide beaucoup à me recentrer."
}

### Stocker l'ID du commentaire
@commentaireId = {{commentaireModo.response.body.id}}


### 6. Julie lit le fil de discussion (Paginé)
GET {{base}}/groupes/{{groupeId}}/publications?page=1&limite=10
Authorization: Bearer {{tokenJulie}}


### 7. Test de Sécurité / Signalement (Ex: Julie signale un contenu inapproprié)
POST {{base}}/signalements
Authorization: Bearer {{tokenJulie}}
Content-Type: {{contentType}}

{
    "publicationId": "{{publicationId}}",
    "categorie": "INQUIETANT"
}

### ----- Favoris -----

### 41. ajouter un favori a Bobby
POST {{base}}/api/v1/resources/{{ressourceId}}/favorite
Authorization: Bearer {{authToken}}

### 42. GET mes favoris (en tant que bobby)
GET {{base}}/api/v1/resources/me/fav
Authorization: Bearer {{authToken}}

### 43. delete le favori précédent a Bobby
DELETE {{base}}/api/v1/resources/{{ressourceId}}/favorite
Authorization: Bearer {{authToken}}

### 44. GET mes favoris à nouveau pour valider la suppression
GET {{base}}/api/v1/resources/me/fav
Authorization: Bearer {{authToken}}

### 45. GET suggestion contextuelle (pour Bobby)
GET {{base}}/api/v1/resources/me/suggestions
Authorization: Bearer {{authToken}}
